language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.3
      dist: trusty
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      sudo: true
install:
    - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then travis_retry pip install coveralls; fi
    - travis_retry pip install -r dev-requirements.txt
script: nosetests
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then coveralls; fi
